apiVersion: v1
kind: Service
metadata:
  name: drupal-mysql-service
  namespace: drupal
spec:
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
  selector:
    app: drupal-mysql

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal-mysql
  namespace: drupal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal-mysql
  template:
    metadata:
      labels:
        app: drupal-mysql
    spec:
      containers:
        - 
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root_password
            - name: MYSQL_DATABASE
              value: drupal-database
          image: "mysql:5.7"
          name: cont-drupal-mysql
          ports:
            - containerPort: 3306
              name: mysql
              protocol: TCP
          volumeMounts:
            - mountPath: "/data"
              name: drupal-pv-mysql
              subPath: dbdata
      volumes:
        - name: drupal-pv-mysql
          persistentVolumeClaim:
            claimName: drupal-pvc-mysql
